cars = [
    {"name": "Civic",   "marca": "Honda", 		"year": 2020, "color": "black", 	"engine": "2.0"},
    {"name": "Accord",  "marca": "Honda", 		"year": 2021, "color": "white", 	"engine": "2.0"},
    {"name": "HRV",     "marca": "Honda",  		"year": 2022, "color": "blue", 		"engine": "1.8"},
    {"name": "Corolla", "marca": "Toyota", 		"year": 2021, "color": "black", 	"engine": "2.0"},
    {"name": "Camry",   "marca": "Toyota", 		"year": 2020, "color": "black", 	"engine": "2.5"},
    {"name": "RAV4",    "marca": "Toyota", 		"year": 2022, "color": "black", 		"engine": "2.5"},
    {"name": "Model 3", "marca": "Tesla", 		"year": 2022, "color": "white", 	"engine": "electric"},
    {"name": "Model Y", "marca": "Tesla", 		"year": 2023, "color": "black", 	"engine": "electric"},
    {"name": "Model S", "marca": "Tesla", 		"year": 2021, "color": "red", 		"engine": "electric"},
    {"name": "Mustang", "marca": "Ford", 		"year": 2019, "color": "red", 		"engine": "5.0"},
    {"name": "Fusion",  "marca": "Ford", 		"year": 2020, "color": "white", 	"engine": "2.0"},
    {"name": "Explorer","marca": "Ford", 		"year": 2022, "color": "black", 	"engine": "3.0"},
    {"name": "A3",      "marca": "Audi", 		"year": 2021, "color": "white", 	"engine": "1.4"},
    {"name": "A4",      "marca": "Audi", 		"year": 2020, "color": "black", 	"engine": "2.0"},
    {"name": "Q5",      "marca": "Audi", 		"year": 2022, "color": "blue", 		"engine": "2.0"},
    {"name": "320i",    "marca": "BMW", 		"year": 2021, "color": "black", 	"engine": "2.0"},
    {"name": "X1",      "marca": "BMW", 		"year": 2022, "color": "white", 	"engine": "2.0"},
    {"name": "X5",      "marca": "BMW", 		"year": 2020, "color": "grey", 		"engine": "3.0"},
    {"name": "C200",    "marca": "Mercedes", 	"year": 2021, "color": "black", 	"engine": "2.0"},
    {"name": "GLA200",  "marca": "Mercedes", 	"year": 2022, "color": "white", 	"engine": "1.6"},
    {"name": "GLE450",  "marca": "Mercedes", 	"year": 2023, "color": "silver", 	"engine": "3.0"},
    {"name": "Golf",    "marca": "Volkswagen", 	"year": 2020, "color": "blue", 		"engine": "1.4"},
    {"name": "Jetta",   "marca": "Volkswagen", 	"year": 2021, "color": "white", 	"engine": "1.4"},
    {"name": "Tiguan",  "marca": "Volkswagen", 	"year": 2022, "color": "black", 	"engine": "2.0"},
    {"name": "Compass", "marca": "Jeep", 		"year": 2021, "color": "white", 	"engine": "2.0"},
    {"name": "Renegade","marca": "Jeep", 		"year": 2020, "color": "red", 		"engine": "1.8"},
    {"name": "Wrangler","marca": "Jeep", 		"year": 2022, "color": "green", 	"engine": "3.6"},
    {"name": "Duster",  "marca": "Renault", 	"year": 2021, "color": "white", 	"engine": "1.6"},
    {"name": "Kwid",    "marca": "Renault", 	"year": 2020, "color": "orange", 	"engine": "1.0"},
    {"name": "Sandero", "marca": "Renault", 	"year": 2022, "color": "grey", 		"engine": "1.6"}
]